version: '3'
services:
  app:
    container_name: app
    image: phpfpm-nginx-centos8
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    tmpfs:
      - /run
      - /run/php-fpm
    volumes:
        - ./server/config/hosts/:/etc/nginx/conf.d/
        - ./server/config/www.conf:/etc/php-fpm.d/www.conf
        - ./app1:/code1
        - ./app2:/code2
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
        - code-network
  app1:
    container_name: app1
    image: phpfpm-nginx-centos8
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    tmpfs:
      - /run
      - /run/php-fpm
    volumes:
        - ./server/config/hosts/app1.conf:/etc/nginx/conf.d/default.conf
        - ./server/config/www.conf:/etc/php-fpm.d/www.conf
        - ./app1:/code1
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
        - code-network
  app2:
    container_name: app2
    image: phpfpm-nginx-centos8
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    tmpfs:
      - /run
      - /run/php-fpm
    volumes:
        - ./server/config/hosts/app2.conf:/etc/nginx/conf.d/default.conf
        - ./server/config/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        - ./server/config/www.conf:/etc/php-fpm.d/www.conf
        - ./app2:/code2
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
        - code-network
networks:
    code-network:
        driver: bridge